INSERT INTO Teams (api_football_id, name, logo_url) VALUES
(2227, 'Tombense', 'https://media.api-sports.io/football/teams/2227.png'),
(2232, 'Sao Jose', 'https://media.api-sports.io/football/teams/2232.png'),
(7772, 'Confiança', 'https://media.api-sports.io/football/teams/7772.png'),
(148, 'Londrina', 'https://media.api-sports.io/football/teams/148.png'),
(755, 'Nautico Recife', 'https://media.api-sports.io/football/teams/755.png'),
(7865, 'São Bernardo', 'https://media.api-sports.io/football/teams/7865.png'),
(1198, 'Remo', 'https://media.api-sports.io/football/teams/1198.png'),
(7814, 'Volta Redonda', 'https://media.api-sports.io/football/teams/7814.png'),
(7770, 'Caxias', 'https://media.api-sports.io/football/teams/7770.png'),
(13975, 'Athletic Club', 'https://media.api-sports.io/football/teams/13975.png'),
(7774, 'Floresta', 'https://media.api-sports.io/football/teams/7774.png'),
(1197, 'Botafogo PB', 'https://media.api-sports.io/football/teams/1197.png'),
(137, 'Figueirense', 'https://media.api-sports.io/football/teams/137.png'),
(1195, 'Ferroviario', 'https://media.api-sports.io/football/teams/1195.png'),
(1221, 'Ypiranga-RS', 'https://media.api-sports.io/football/teams/1221.png'),
(150, 'CSA', 'https://media.api-sports.io/football/teams/150.png'),
(7826, 'Ferroviária', 'https://media.api-sports.io/football/teams/7826.png'),
(754, 'ABC', 'https://media.api-sports.io/football/teams/754.png'),
(1202, 'Aparecidense', 'https://media.api-sports.io/football/teams/1202.png'),
(155, 'Sampaio Correa', 'https://media.api-sports.io/football/teams/155.png'),
(130, 'Gremio', 'https://media.api-sports.io/football/teams/130.png'),
(134, 'Atletico Paranaense', 'https://media.api-sports.io/football/teams/134.png'),
(1062, 'Atletico-MG', 'https://media.api-sports.io/football/teams/1062.png'),
(140, 'Criciuma', 'https://media.api-sports.io/football/teams/140.png'),
(118, 'Bahia', 'https://media.api-sports.io/football/teams/118.png'),
(124, 'Fluminense', 'https://media.api-sports.io/football/teams/124.png'),
(127, 'Flamengo', 'https://media.api-sports.io/football/teams/127.png'),
(126, 'Sao Paulo', 'https://media.api-sports.io/football/teams/126.png'),
(120, 'Botafogo', 'https://media.api-sports.io/football/teams/120.png'),
(144, 'Atletico Goianiense', 'https://media.api-sports.io/football/teams/144.png'),
(121, 'Palmeiras', 'https://media.api-sports.io/football/teams/121.png'),
(119, 'Internacional', 'https://media.api-sports.io/football/teams/119.png'),
(794, 'RB Bragantino', 'https://media.api-sports.io/football/teams/794.png'),
(133, 'Vasco DA Gama', 'https://media.api-sports.io/football/teams/133.png'),
(154, 'Fortaleza EC', 'https://media.api-sports.io/football/teams/154.png'),
(135, 'Cruzeiro', 'https://media.api-sports.io/football/teams/135.png'),
(1193, 'Cuiaba', 'https://media.api-sports.io/football/teams/1193.png'),
(136, 'Vitoria', 'https://media.api-sports.io/football/teams/136.png'),
(152, 'Juventude', 'https://media.api-sports.io/football/teams/152.png'),
(131, 'Corinthians', 'https://media.api-sports.io/football/teams/131.png');
